default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: test123
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

development:
  <<: *default
  database: todoapp_development

staging:
  <<: *default
  database: todoapp_staging

production:
  <<: *default
  database: todoapp_production

test:
  <<: *default
  database: todoapp_test
